#!/bin/bash

# Import install functions.
source "./install.sh"

echo "Preparing installation..."

# Register a cleanup function to be called on the EXIT signal. Regardless of the exit code.
trap handle_exit_signal EXIT

# Extract and install private browsing icon.
prepare_temp_dir
determine_firefox_install_path
install_private_browsing_icon
