#!/bin/bash

# Extract and move icon
mkdir -p /tmp/firefoxprofile_installer
if [[ -e /usr/lib/firefox/browser/omni.ja ]]; then
    unzip /usr/lib/firefox/browser/omni.ja -c "chrome/browser/skin/classic/browser/privatebrowsing/favicon.svg" -d /tmp/firefoxprofile_installer > /dev/null 2>&1
else
    unzip /usr/lib/firefox-esr/browser/omni.ja -c "chrome/browser/skin/classic/browser/privatebrowsing/favicon.svg" -d /tmp/firefoxprofile_installer > /dev/null 2>&1
fi

sudo mkdir -p /usr/share/pixmaps/
sudo mv /tmp/firefoxprofile_installer/chrome/browser/skin/classic/browser/privatebrowsing/favicon.svg /usr/share/pixmaps/private_browsing_firefox.svg
rm -rf /tmp/firefoxprofile_installer
